### ISSUE TITLE
What is " \xe2 " need?

### ISSUE THREAD

**Issue by hanwoo1** [Dylan5797/scratchapi#17]
What is " \xe2 " need?

**Comment by PolyEdge** [comment]
First off, the question's a bit vague. A line number or something would be helpful.
Second, why is this an issue? If I remember correctly, \xe2 is part of the char encodings for the cloud symbol (☁), which is used for the TCP interface for cloud sessions.

I'm going to close this assuming it's just a question, and if you're having trouble, open another issue and make sure to include a line number and stack trace.

Thanks!

**Comment by hanwoo1** [comment]
Thank you!
