### ISSUE TITLE
Cloud server doesn't take any notice of 'value' when creating cloudvar

### ISSUE THREAD

**Issue by TheLogFather** [Dylan5797/scratchapi#2]
When creating a cloudvar the server always starts it off at zero - you can't set an initial value (at least, I've never seen it work).

So it seems not really worth requiring the value parameter for create_var. (However, keep it as an optional parameter, for backwards-compatibility, and in case it does ever become supported.)

**Comment by PolyEdge** [comment]
Oops! I'll push that soon.

Would you like to contribute?

**Comment by TheLogFather** [comment]
Curiously, I've just noticed that if you set a non-existent cloudvar, then it does create it, along with the value. But there's no 'create_var' log entry, interestingly (only the 'set_var').

I guess, for completeness, you could add code for 'delete' and 'rename' capabilities, to go with 'create'.

TBH, though, I'm not sure how much use any of these three are (even 'create'), given that a pre-existing project never notices anything about vars it doesn't already have a record of in its JSON (unfortunately...), and deleting a cloudvar it does know about effectively has no impact on the project, since it gets created again as soon as the project changes it (and it continues to get the original value whenever it uses it after it's been deleted).

As for contributing, I'm not sure there's much else I'd do, since you've already covered so much – it was just a couple of minor thoughts I had which arose from when I was messing around with these things before.

**Comment by TheLogFather** [comment]
As an aside, I'm also slightly bemused that any user (Scratcher) can create/delete cloudvars for any project, even if they don't own it... :/
(I guess, given the above, it effectively doesn't matter, but still...)

**Comment by PolyEdge** [comment]
I thought that deleting only removes the var from the JSON. What is the method name?

**Comment by TheLogFather** [comment]
Ohhh, oops... forgot that was something I added...

In CloudSession, I added this:

```
def delete_var(self, name):
    self._send('delete', 'â ' + name, 0)
```

The method is just 'delete'.

**Comment by PolyEdge** [comment]
Now just testing and pushing...

**Comment by TheLogFather** [comment]
OK, great!

One thing I've been wanting to investigate for a while now is the pushing of new cloudvar values to a project. In other words, getting updates without polling the varserver URL.

Wondering if you've looked into this at all? -It'd make a really nice (and exclusive?) addition to this framework if we could get it going, but I've not tried to figure it out so far. (I'm not even sure what port they come from, though I've noticed that I fall back to https polling if I block port 843, and not just port 531, so maybe that's the place to look?)

**Comment by TheLogFather** [comment]
Ah, sorry, just noticed the code snippet I gave above doesn't match what you've got in CloudSession._send... The code above was after I'd been messing around with it somewhat, experimenting in various ways.

Obviously, it should be more like:

```
def delete_var(self, name):
    self._send('delete', {'name': '☁ ' + name})
```

Also, to rename a cloudvar:

```
def rename_var(self, oldname, newname):
    self._send('rename', {'name': '☁ ' + oldname, 'new_name': '☁ ' + newname})
```

Hope that makes more sense!

**Comment by PolyEdge** [comment]
Yes, I figured out the delete code, I just didn't know what to put into rename

**Comment by TheLogFather** [comment]
(Sorry... again... fixed the rename method above - didn't mean to leave it as 'create', should've been 'rename'. Agh, maybe it's time I got some sleep :/ )

**Comment by PolyEdge** [comment]
Ok, I'll test and push

**Comment by PolyEdge** [comment]
Done.
