### ISSUE TITLE
Getting message HTML fails

### ISSUE THREAD

**Issue by micahlt** [Dylan5797/scratchapi#21]
I'm using `scratchapi` in a virtual environment ([repl.it](http://repl.it)) and using it to generate my message page HTML using the command `print(scratchapi.ScratchUserSession.messages.get_message_html())`.  Oddly, this generates the response `<Response [200]>` which sounds like an HTML error.  I checked out some old issues, and #15 @PolyEdge stated that an HTML parser would be needed to view that kind of data.  I attempted to install the `html` package, but that doesn't solve anything.  Help?

**Comment by PolyEdge** [comment]
1. the object you're seeing is a requests response object, the html will be stored in scratchapi.ScratchUserSession.messages.get_message_html().text
2. i personally use beautifulsoup to parse html, with the lxml parser
`pip install beautifulsoup4` and `pip install lxml` then `from bs4 import BeautifulSoup` and `parser = BeautifulSoup(etcetc..get_message_html(), "lxml")`

**Comment by micahlt** [comment]
Wow, this project is still active!  ;-) All right, I didn't know that the `text` would need to be specified.  Thanks for the help!
