### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by ghost** [Dylan5797/scratchapi#7]
There's no (barely any) documentation for the commands. Please work on this!

**Comment by PolyEdge** [comment]
I have most of the documentation in my local git copy.

I am currently reviewing it.

**Comment by ghost** [comment]
Estimated release time?

**Comment by PolyEdge** [comment]
I haven't really planned a release date. I will have it by Friday next week.

**Comment by PolyEdge** [comment]
Might be late. I'm sick :(

**Comment by ghost** [comment]
still waiting :(

**Comment by haylinmoore** [comment]
:( we need that doc

**Comment by PolyEdge** [comment]
Ok, I got a new laptop and I'm on holidays, so the documentation is 800km away.

I'll re-write it, and push whenever I finish a page.

**Comment by haylinmoore** [comment]
ok

**Comment by ghost** [comment]
Still waiting... :100: :cry:

**Comment by haylinmoore** [comment]
Please I am Still waiting... :100: :cry:

**Comment by PolyEdge** [comment]
I am really sorry, I have a lot going on at the moment.

**Comment by haylinmoore** [comment]
Waiting

**Comment by skistaddy** [comment]
@herohamp Stop nagging him. He said he was busy, :)

**Comment by haylinmoore** [comment]
I know I just need it!

**Comment by ghost** [comment]
To be honest most API's are practically useless without any documentation.

**Comment by PolyEdge** [comment]
Read this: https://github.com/Dylan5797/scratchapi/wiki/Class-ScratchUserSession--%7C-Subcommands

**Comment by PolyEdge** [comment]
Is that enough for the moment?

**Comment by ghost** [comment]
yes! :D

**Comment by haylinmoore** [comment]
Yes :D it is amazing!

**Comment by PolyEdge** [comment]
Thanks, I'll add CloudSession and users later.

**Comment by PolyEdge** [comment]
Woah ninja

**Comment by haylinmoore** [comment]
you a ninja

**Comment by jeandrek** [comment]
![HOORAY](https://assets-cdn.github.com/images/icons/emoji/unicode/1f389.png)

**Comment by haylinmoore** [comment]
HOORAY

**Comment by PolyEdge** [comment]
yay

**Comment by jeandrek** [comment]
> Woah ninja

&nbsp;<Wat help>

> you a ninja

What do these posts mean?

**Comment by PolyEdge** [comment]
@Jonathan50 Herohamp posted seconds before I did.

**Comment by micahlt** [comment]
So... still no documentation for other commands... Are we still working on this?
