### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jeandrek** [Dylan5797/scratchapi#8]
Can you put a license (such as MIT/X11, MIT/Expat, GNU (Lesser) General Public License, etc.) on ScratchAPI so people have permission to use it?

**Comment by PolyEdge** [comment]
I added it in

87f8be5ae925192aedea3f632aaf8d85d5f5886e
653a97c9dd878dd75c0df4419f735f1114a9f48c

**Comment by jeandrek** [comment]
cool
